name: arpy-ai-env
channels:
  - defaults
dependencies:
  - python=3.10.2
  - pip
  - pip:
      - openai
      - google-generativeai
      - requests
      - pyttsx3
      - SpeechRecognition
      - python-dotenv
